version: "3.8"
services:
  frontend:
    image: thesis-frontend-dev
    build: ./front
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./front:/home/node/app
      - react-modules:/home/node/app/node_modules
volumes: 
  react-modules:
