version: "3.8"
services:
  frontend:
    image: oms-frontend
    build:
      context: ./front
      dockerfile: Dockerfile-prod
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./front:/home/node/app
      - react-modules:/home/node/app/node_modules
  backend:
    image: oms-backend
    build:
      context: ./back
      dockerfile: Dockerfile-prod
    ports:
      - 8000:80
    volumes:
      - ./back:/var/www/html
      - ./back/docker/php-overrides-prod.ini:/usr/local/etc/php/conf.d/php-overrides.ini
      - lumen-vendor:/var/www/html/vendor
      - lumen-cache:/var/www/html/storage/framework/cache
      - lumen-storage:/var/www/html/storage/app
  db:
    image: mariadb:10.7.1
    env_file:
      - db/.env
    ports:
      - 3306:3306
    volumes:
      - mariadb-store:/var/lib/mysql
volumes:
  react-modules:
  lumen-vendor:
  lumen-cache:
  lumen-storage:
  mariadb-store:
